# Generated by Django 6.0.2 on 2026-02-12 00:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_image', models.ImageField(blank=True, help_text='Customer photo (optional)', null=True, upload_to='testimonials/')),
                ('location', models.CharField(blank=True, help_text='e.g., New York, USA', max_length=200)),
                ('rating', models.IntegerField(help_text='Rating out of 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(help_text="Customer's review")),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by admin')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.accessory')),
                ('purchased_dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.dog')),
            ],
            options={
                'verbose_name': 'Customer Testimonial',
                'verbose_name_plural': 'Customer Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
